//GET TYPES
export const NETWORK_NODE_LOAD_SUCCESSFULL='NETWORK_NODE_LOAD_SUCCESSFULL'
export const NETWORK_NODE_LOAD_FAILED='NETWORK_NODE_LOAD_FAILED'

export const NETWORK_NODE_INFO__LOAD_SUCCESSFULL='NETWORK_NODE_INFO__LOAD_SUCCESSFULL'
export const NETWORK_NODE_INFO__LOAD_FAILED='NETWORK_NODE_INFO__LOAD_FAILED'

//DELETE TYPES
export const NETWORK_NODE_DELETE_FAILED='NETWORK_NODE_DELETE_FAILED'

//UPDATE(PUT/POST) TYPES
export const NETWORK_NODE_UPDATE_FAILED='NETWORK_NODE_UPDATE_FAILED'

// SIDEBAR'S VISIBILITY
export const OPEN_SIDEBAR='OPEN_SIDEBAR';
export const CLOSE_SIDEBAR='CLOSE_SIDEBAR';

// MODAL'S VISIBILITY
export const OPEN_MODAL='OPEN_MODAL';
export const CLOSE_MODAL='CLOSE_MODAL';
